spring:
  datasource:
    url: jdbc:mysql://localhost:3306/User_service
    username: root
    password: Pramod#8792
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # updates tables without dropping them
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
